apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
spec:
  template:
    spec:
      containers:
      - name: intel-gpu-plugin
        volumeMounts:
        - name: podresources
          mountPath: /var/lib/kubelet/pod-resources
      volumes:
      - name: podresources
        hostPath:
          path: /var/lib/kubelet/pod-resources
 