apiVersion: v1
data:
  collectd.conf: |2

    LoadPlugin write_prometheus
    LoadPlugin dpdk_telemetry
    <Plugin dpdk_telemetry>
        ClientSocketPath "/var/run/.client"
        DpdkSocketPath "/var/run/dpdk/rte/telemetry"
    </Plugin>
    <Plugin write_prometheus>
      Port "9103"
    </Plugin>
kind: ConfigMap
metadata:
  name: collectd-config
  namespace: default
