apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: health-metric-demo
data:
  nginx.conf: |
    worker_processes  auto;

    error_log  /tmp/nginx/error.log warn;
    pid        /tmp/nginx/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      server {
        listen 8090; # specify a port higher than 1024 if running as non-root user
        location / {
          add_header Content-Type text/plain;
          return 200 'hello world';
      }
     }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo
  namespace: health-metric-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo 
  template:
    metadata:
      labels:
        app: demo
        telemetry-policy: demo-policy
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop: [ 'ALL' ]
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsUser: 10001
          runAsGroup: 10001
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        - name: conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: tmp
          mountPath: /tmp/nginx
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "200Mi"
            telemetry/scheduling: 1
            cpu: "100m"
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: conf
        configMap:
          name: nginx-conf
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: demo-policy
                    operator: NotIn
                    values:
                      - violating

