apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.serviceNamespace }}
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    app: {{ .Values.appName }}
