apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policy-handler
rules:
- apiGroups: ["telemetry.intel.com"]
  resources: ["taspolicies"]
  verbs: ["get", "watch", "list", "delete", "update"]
- apiGroups: ["custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch","update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]

---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: handle-policies
  subjects:
    - kind: ServiceAccount
      name: telemetry-aware-scheduling-service-account
      namespace: default
  roleRef:
    kind: ClusterRole
    name: policy-handler
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telemetry-aware-scheduling-service-account