apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: collectd 
    app.kubernetes.io/version: v5.11
  name: collectd
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9103
    protocol: TCP
    targetPort: 9103
  selector:
    app.kubernetes.io/name: collectd
