run:
  tests: true
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable-all: true
  disable:
    - paralleltest
    - depguard
    - exhaustivestruct

linters-settings:
  gofmt:
    simplify: true
  gofumpt:
    lang-version: "1.21"
  golint:
    min-confidence: 0.9
  govet:
    check-shadowing: true
    enable:
    - "fieldalignment"
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 31
  funlen:
    lines: 70
  cyclop:
    max-complexity: 10

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        # Until the testing package allows pinning variables disable scopelint
        # for tests. See https://github.com/kyoh86/scopelint/issues/4.
        - scopelint
        - funlen
        - goimports
        - gofmt
        - unparam
        - exhaustivestruct
        - exhaustruct
        - gocyclo
        - cyclop
        - revive
