apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb-example
  template:
    metadata:
      labels:
        app: bb-example
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: bb-example
        image: busybox:1.33.1
        command: ['sh', '-c', 'echo The gpu resource request app is running! && sleep 6000']
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 100Mi
            gpu.intel.com/i915: 1
            gpu.intel.com/millicores: 100
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          capabilities:
            drop: [ "ALL" ]