apiVersion: apps/v1
kind: Deployment
metadata:
  name: same-gpu-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: same-gpu-example
  template:
    metadata:
      labels:
        app: same-gpu-example
      annotations:
      #List containers that needs to be in same GPU
        gas-same-gpu: same-gpu-container1,same-gpu-container3
    spec:
      containers:
      - name: &container1 same-gpu-container1
        image: busybox:1.33.1
        env:
        - name: MY_CONTAINER_NAME
          value: *container1
        command: ['sh', '-c', 'echo $MY_CONTAINER_NAME && ls -ltr /dev/dri && sleep 6000']
        resources:
          limits:
            gpu.intel.com/i915: 1
            gpu.intel.com/millicores: 400
      - name: &container2 same-gpu-container2
        image: busybox:1.33.1
        env:
        - name: MY_CONTAINER_NAME
          value: *container2
        command: ['sh', '-c', 'echo $MY_CONTAINER_NAME && ls -ltr /dev/dri && sleep 6000']
        resources:
          limits:
            gpu.intel.com/i915: 1
            gpu.intel.com/millicores: 300
      - name: &container3 same-gpu-container3
        image: busybox:1.33.1
        env:
        - name: MY_CONTAINER_NAME
          value: *container3
        command: ['sh', '-c', 'echo $MY_CONTAINER_NAME && ls -ltr /dev/dri && sleep 6000']
        resources:
          limits:
            gpu.intel.com/i915: 1
            gpu.intel.com/millicores: 400
      - name: &container4 same-gpu-container4
        image: busybox:1.33.1
        env:
        - name: MY_CONTAINER_NAME
          value: *container4
        command: ['sh', '-c', 'echo $MY_CONTAINER_NAME && ls -ltr /dev/dri && sleep 6000']
        resources:
          limits:
            gpu.intel.com/i915: 1
            gpu.intel.com/millicores: 300
