apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: collectd 
    app.kubernetes.io/version: v5.11 
  name: collectd
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: collectd 
      app.kubernetes.io/version: v5.11 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: collectd
        app.kubernetes.io/version: v5.11 
    spec:
      containers:
      - image: intel/observability-collectd:1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop: [ 'ALL' ]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          allowPrivilegeEscalation: false
          runAsGroup: 10001
          seccompProfile:
            type: RuntimeDefault
        name: collectd
        command: ["/bin/sh", "-c","../../run_collectd.sh"]
        resources:
          limits:
            cpu: 150m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - name: config
          mountPath: /opt/collectd/etc/collectd.conf
          subPath: collectd.conf
        - name: pkgpower
          mountPath: /opt/collectd/etc/python-scripts/pkgpower.py
          subPath: pkgpower.py
        ports:
        - containerPort: 9103
          protocol: TCP
      volumes:
      - name: config
        configMap:
          name: collectd-config
      - name: pkgpower
        configMap:
          name: pkgpower
