apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: collectd 
    app.kubernetes.io/version: v5.11
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9103'
  name: collectd
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9103
    protocol: TCP
    targetPort: 9103
  selector:
    app.kubernetes.io/name: collectd
