apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-aware-scheduling
  namespace: default 
  labels:
    app: tas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tas
  template:
    metadata:
      labels:
        app: tas
    spec:
      serviceAccountName: telemetry-aware-scheduling-service-account
      containers:
      - name: tasext
        command:
        - /extender
        - --syncPeriod=2s
        - --cert=/tas/cert/tls.crt
        - --key=/tas/cert/tls.key
        - --cacert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --v=2
        image: intel/telemetry-aware-scheduling
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
        volumeMounts:
        - name: certs
          mountPath: /tas/cert
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "100m"
      volumes:
      - name: certs
        secret:
          secretName: extender-secret
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists

