name: Go build and test

on:
  workflow_call:
    inputs:
      runsOn:
        required: false
        type: string
        default: 'ubuntu-latest'
      goVersion:
        required: false
        type: string
        default: 1.17

jobs:
  build-test:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.goVersion }}
      - name: Build
        run: make test
      - name: Test
        run: make build

