name: Go build and test

on:
  workflow_call:
    inputs:
      runsOn:
        required: false
        type: string
        default: 'ubuntu-latest'
      goVersion:
        required: false
        type: string
        default: 1.20.5

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "${{ inputs.goVersion }}"
      - name: Build
        run: make build
      - name: Image
        run: make image
      - name: Test
        run: make test

